version: '3.1'

networks:
    backend:
        driver: bridge

services:
    booking:
        image: mysql:8.0
        container_name: booking
        volumes:
            - ../data/booking:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=booking
            - MYSQL_DATABASE=booking
            - MYSQL_USER=booking
            - MYSQL_PASSWORD=booking
        ports:
            - "8006:3306"
        networks:
            - backend
    phpmyadmin_booking:
        container_name: phpmyadmin_booking
        image: phpmyadmin
        restart: always
        ports:
            - "8093:80"
        environment:
            - PMA_HOST=booking
        depends_on:
            - booking
        networks:
            - backend
    app:
        build:
            context: ..
            dockerfile: ./docker/php/Dockerfile
            args:
                # Подставьте ваш UID/GID (в WSL обычно 1000/1000)
                PUID: 1000
                PGID: 1000
        container_name: laravel_app
        working_dir: /var/www/html
        volumes:
            - ..:/var/www/html
        depends_on:
            - booking
        networks:
            - backend
        environment:
            # чтобы Composer не требовал интерактива
            COMPOSER_ALLOW_SUPERUSER: 1
            PHP_MEMORY_LIMIT: 512M
    nginx:
        image: nginx:1.27-alpine
        container_name: laravel_nginx
        depends_on:
            - app
        ports:
            - "8080:80"
        volumes:
            - ..:/var/www/html
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
        networks:
            - backend
